# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6YyWDx0W4QoizjRrKI35XGxcnWH8y9a
"""

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

# Read CSV file
data = pd.read_csv("/content/tips.csv")

# Show first few rows
print(data.head())
data.info()
data.isnull().sum

# Plot
sns.relplot(x="total_bill", y="tip", data=data)
plt.show()

sns.histplot(data["total_bill"], bins=20, kde=True)
plt.title("Distribution of Total Bill")
plt.show()

sns.countplot(x="day",  data=data)
plt.show()

sns.boxplot(x="day", y="total_bill", data=data)
plt.title("Box Plot of Total Bill by Day")
plt.show()

# 1️⃣ Scatter Plot
sns.scatterplot(x="total_bill", y="tip", data=data)
plt.title("Scatter Plot - Total Bill vs Tip")
plt.show()

# 2️⃣ Bar Plot
sns.barplot(x="day", y="total_bill", data=data)
plt.title("Bar Plot - Average Total Bill by Day")
plt.show()

# 3️⃣ Heatmap
corr = data.corr(numeric_only=True)
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Heatmap - Correlation Matrix")
plt.show()

# 4️⃣ Pair Plot
sns.pairplot(data)
plt.suptitle("Pair Plot - Pairwise Relationships", y=1.02)
plt.show()

# Create subplots (2 rows x 2 columns)
fig, axes = plt.subplots(2, 2, figsize=(15, 12))

# 1️⃣ Scatter Plot
sns.scatterplot(x="total_bill", y="tip", data=data, ax=axes[0, 0])
axes[0, 0].set_title("Total Bill vs Tip")

# 2️⃣ Bar Plot
sns.barplot(x="day", y="total_bill", data=data, ax=axes[0, 1])
axes[0, 1].set_title("Average Total Bill by Day")

# 3️⃣ Box Plot
sns.boxplot(x="sex", y="tip", data=data, ax=axes[1, 0])
axes[1, 0].set_title("Tip Distribution by Gender")

# 4️⃣ Heatmap
corr = data.corr(numeric_only=True)
sns.heatmap(corr, annot=True, cmap="coolwarm", ax=axes[1, 1])
axes[1, 1].set_title("Correlation Heatmap")

# Main title and layout
plt.suptitle("Tips Dataset Dashboard", fontsize=18, fontweight="bold", y=1.02)
plt.tight_layout()
plt.show()

#print("Insights Summary")
print("------------------------------------")
print("1. The tip amount increases as the total bill increases, showing a positive correlation.")
print("2. Average total bills are higher on weekends (Saturday and Sunday) compared to weekdays.")
print("3. Male customers tend to give slightly higher tips on average than female customers.")
print("4. The heatmap shows a strong correlation between total_bill and tip.")
print("5. Overall, weekend spending and tipping trends are higher than weekday trends.")