# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DYStqWSbuiEIXOZR-OXYjF-6oTmNArWj
"""



# Task 1: List operations (max, min, sum, average)
numbers = [14, 29, 99, 85, 15, 25]

print("Numbers List:", numbers)
print("Maximum:", max(numbers))
print("Minimum:", min(numbers))
print("Sum:", sum(numbers))
print("Average:", sum(numbers) / len(numbers))


# Task 2: Word frequency count in a sentence
sentence = "Python is easy and Python is powerful"
words = sentence.split()
frequency = {}

for word in words:
    frequency[word] = frequency.get(word, 0) + 1

print("\nSentence:", sentence)
print("Word Frequencies:", frequency)


# Task 3: Prime number checker
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Testing prime function
print("\nIs 7 prime?", is_prime(7))
print("Is 15 prime?", is_prime(15))
print("Is 2 prime?", is_prime(2))