# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12-1EC9qyypEYKuG5MQneezYy1kWs9yh3
"""

import pandas as pd
import matplotlib.pyplot as plt
# 1. LOAD AND INSPECT DATA
df = pd.read_csv("sales_data.csv")   # <-- put your CSV name here

print(df.head())          # first 5 rows
print(df.dtypes)          # column types
print(df.isnull().sum())  # missing values

# 2. DATA CLEANING
# Convert columns to numeric (if needed)
df["Units_Sold"] = pd.to_numeric(df["Units_Sold"], errors="coerce")
df["Unit_Price"] = pd.to_numeric(df["Unit_Price"], errors="coerce")
df["Marketing_Spend"] = pd.to_numeric(df["Marketing_Spend"], errors="coerce")

# Fill missing numeric values with 0
df = df.fillna(0)

# Create new column Revenue
df["Revenue"] = df["Units_Sold"] * df["Unit_Price"]


# 3. DESCRIPTIVE STATISTICS
# Total revenue per product
total_revenue = df.groupby("Product")["Revenue"].sum()
print("\nTotal Revenue per Product:\n", total_revenue)
# Average units sold per product
avg_units = df.groupby("Product")["Units_Sold"].mean()
print("\nAverage Units Sold per Product:\n", avg_units)

# Week with highest sales (units)
week_sales = df.groupby("Week")["Units_Sold"].sum()
print("\nWeek with Highest Sales:\n", week_sales.idxmax())
# 4. DATA VISUALIZATION
# Line plot: Units Sold over Weeks
plt.figure(figsize=(8,5))
for product in df["Product"].unique():
    data = df[df["Product"] == product]
    plt.plot(data["Week"], data["Units_Sold"], marker='o', label=product)

plt.title("Units Sold Over Weeks")
plt.xlabel("Week")
plt.ylabel("Units Sold")
plt.legend()
plt.show()

# Bar chart: Total Revenue per Product
total_revenue.plot(kind="bar", title="Total Revenue by Product")
plt.xlabel("Product")
plt.ylabel("Revenue")
plt.show()

# Scatter: Marketing Spend vs Units Sold
plt.scatter(df["Marketing_Spend"], df["Units_Sold"])
plt.title("Marketing Spend vs Units Sold")
plt.xlabel("Marketing Spend")
plt.ylabel("Units Sold")
plt.show()

# 5. DATA ANALYSIS
# Correlation
correlation = df["Marketing_Spend"].corr(df["Units_Sold"])
print("\nCorrelation between Marketing Spend and Units Sold:", correlation)

# Identify product with highest growth
growth = df.groupby("Product")["Units_Sold"].sum()
print("\nProduct with Highest Sales Growth:", growth.idxmax())

# Insights
print("\n--- Insights ---")
print("1. Product with highest revenue:", total_revenue.idxmax())
print("2. Highest sales happened in week:", week_sales.idxmax())
print("3. Marketing & Units correlation:", correlation)