# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CER16gDMdmfi8IsanFXF8pO96WndiHFW
"""

import csv
# STEP 1: Read Employees Data
employees = {}
with open("zenvy_employees.csv", "r") as file:
    reader = csv.DictReader(file)
    for row in reader:
        employees[row["employee_id"]] = {
            "name": row["employee_name"],
            "basic": int(row["base_salary"])
        }

# STEP 2: Read Attendance Data
attendance = {}
with open("zenvy_attendance.csv", "r") as file:
    reader = csv.DictReader(file)
    for row in reader:
        attendance[row["employee_id"]] = int(float(row["overtime_hours"]))
# STEP 3: Read Payroll Data
payroll = {}
with open("zenvy_payroll.csv", "r") as file:
    reader = csv.DictReader(file)
    for row in reader:
        payroll[row["employee_id"]] = {
            "gross_salary": int(row["gross_salary"]),
            "tax":int(float(row["tax_deduction"])),
            "pf": int(float(row["pf_deduction"])),
        }
# STEP 4: Salary Calculation Function
OVERTIME_RATE = 200  # ₹200 per hour
def calculate_salary(employee_id):

    base_salary = employees[employee_id]["basic"]
    overtime_hours = attendance.get(employee_id, 0)
    overtime_pay = overtime_hours * OVERTIME_RATE

    gross_salary = base_salary + overtime_pay

    tax = payroll[employee_id]["tax"]
    pf = payroll[employee_id]["pf"]

    total_deduction = tax + pf
    net_salary = gross_salary - total_deduction

    final_pay = net_salary + overtime_pay

    return gross_salary, total_deduction, overtime_pay, net_salary, final_pay
# STEP 5: Print Salary Output (Testing)
print("PAYROLL CALCULATION OUTPUT")
for employee_id in payroll:
    gross, total_deduction, overtime_pay, net, final_pay = calculate_salary(employee_id)

    print(
        " Emp ID:", employee_id,
        "| Gross:", gross,
        "| Total Deduction:", total_deduction,
        "| Overtime Pay:", overtime_pay,
        "| Net:", net,
        "|final pay:",final_pay
    )
# STEP 6: Generate Initial CSV Report
with open("week3_payroll_report.csv", "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["Emp ID", "Name", "Gross Salary","Total_deduction","Overtime_Pay","Net Salary","final pay"])

    for emp_id in employees:
        gross,total_deduction,Overtime_Pay,net,final_pay = calculate_salary(emp_id)
        writer.writerow([
            emp_id,
            employees[emp_id]["name"],
            gross,
            total_deduction,
            Overtime_Pay,
            net,
            final_pay
        ])

print("\nCSV report generated: week3_payroll_report.csv")