# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJuL0qyNHqH0XEaf1Fd2JSYpvVc2gCPy
"""

import json
import requests

# --- Q1: Convert a Python dictionary into JSON and save it in a file ---
data = {
    "name": "Ram charan",
    "age": 25,
    "city": "Hyd"
}
with open("data.json", "w") as file:
    json.dump(data, file, indent=5)
print("Q1: Data saved to data.json")

# --- Q2: Load data from a JSON file and print all values of a specific key ---
with open("data.json", "r") as file:
    data = json.load(file)
print("Q2: Name:", data.get("name"))

# --- Q3: Parse a JSON string of multiple users and print the name of users older than 25 ---
json_string = '''
[
    {"name": "sai", "age": 24},
    {"name": "ram", "age": 25},
    {"name": "virat", "age": 27},
    {"name": "kohil", "age": 22}
]
'''
users = json.loads(json_string)
print("Q3: Users older than 25:")
for user in users:
    if user["age"] > 25:
        print(user["name"])

# --- Q4: Fetch data from an API and print the titles of the first 10 posts ---
response = requests.get("https://jsonplaceholder.typicode.com/posts")
posts = response.json()
print("Q4: Titles of the first 10 posts:")
for post in posts[:10]:
    print(post["title"])

# --- Q5: Send a POST request with custom data and print the response ---
post_data = {
    "title": "My Custom Post",
    "body": "This is the body of the post",
    "userId": 101
}
response = requests.post("https://jsonplaceholder.typicode.com/posts", json=post_data)
print("Q5: Response from server:")
print(response.json())

# --- Q6: Check if a website returns status code 200 ---
url = "https://www.amazon.in/events/greatsummersale"
response = requests.get(url)
if response.status_code == 200:
    print(f"Q6: {url} is up! Status Code: 200")
else:
  print(f"Q6: {url} returned Status Code: {response.status_code}")